apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: icgroup
  labels:
    app: odoo
    env: prod
type: Opaque
data:
  ODOO_USER: YWFpc3NhdG91  # "aissatou" encodé en base64
  ODOO_PASSWORD: bGFwdXJlY2xhc3NlZHBm  # "lapureclassepf" encodé en base64

