apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
spec:
  selector:
    app: odoo
  type: NodePort
  ports:
    - port: 8069  # Port interne
      nodePort: 30069  # Port externe accessible
      protocol: TCP

