apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
      - name: ic-webapp
        image: aissatoumarone/ic-webapp:1.0
        ports:
        - containerPort: 8080
          name: ic-webapp
        env:
        - name: ODOO_URL
          value: "http://192.168.56.10:30069/"
        - name: PGADMIN_URL
          value: "http://192.168.56.10:30050/"

