apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-service
  namespace: icgroup
spec:
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 80          # Port interne du service
      targetPort: 8080   # Port du conteneur où l'application écoute
      nodePort: 30080    # Port externe accessible depuis l'extérieur du cluster
  type: NodePort

