apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - port: 80  # Port interne dans le cluster (le port utilisé dans le Deployment)
      nodePort: 30050  # Port accessible en dehors du cluster (dans la plage 30000-32767)
      protocol: TCP

