apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      env: prod
  template:
    metadata:
      labels:
        app: pgadmin
        env: prod
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "nastoumarone1@gmail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - containerPort: 5050  # Utilisez le port 5050 pour pgAdmin
          volumeMounts:
            - name: pgadmin-config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json  # Le fichier spécifique du configMap sera monté ici
            - name: pgadmin-pvc
              mountPath: /var/lib/pgadmin  # Pour persister les données de pgAdmin
      volumes:
        - name: pgadmin-config-volume
          configMap:
            name: pgadmin-config  # Utilise le ConfigMap pour récupérer le fichier servers.json
        - name: pgadmin-pvc
          persistentVolumeClaim:
            claimName: pgadmin-pvc  # PVC pour persister les données

