apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: icgroup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Vous pouvez ajuster la taille selon vos besoins
  storageClassName: standard  # Cela dépend de votre configuration de stockage

