apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: icgroup
  labels:
    app: postgres
    env: prod
type: Opaque
data:
  POSTGRES_USER: YWFpc3NhdG91  # "aissatou" en base64
  POSTGRES_PASSWORD: bGFwdXJlY2xhc3NlZHBm  # "lapureclassepf" en base64
stringData:
  POSTGRES_DB: postgres  # "postgres" sans encodage en base64

